
services:
  mysql:
    image: mysql:8.0
    container_name: netology-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  app:
    image: openjdk:11.0.11-jre-slim
    container_name: netology-app
    depends_on:
      - mysql
    ports:
      - "8080:9999"
    
    environment:
      DB_URL: "jdbc:mysql://mysql:3306/app?allowPublicKeyRetrieval=true&useSSL=false"
      DB_USER: "app"
      DB_PASS: "pass"
    volumes:
      - ./app-deadline.jar:/app.jar
  
    command: java -jar /app.jar
    restart: unless-stopped